### ISSUE TITLE
Support bundling into draft 7 and below

### ISSUE THREAD

**Issue by jonaslagoni** [hyperjump-io/json-schema-bundle#3]
If we want to bundle schemas from prior to JSON Schema 2019-09 `$defs` should be `definitions`, would it make sense to add such a feature?

I was thinking we could look up the `$schema` for the root schema (which we bundle stuff into), and if it matches any of the prior versions to 2019-09 it uses `definitions` instead.

Or would it make more sense to provide such a feature through an option?

**Comment by jdesrosiers** [comment]
I fixed this yesterday.Try pulling down changes and let me know if you find any other issues.
