### ISSUE TITLE
Library not available on npm

### ISSUE THREAD

**Issue by jonaslagoni** [hyperjump-io/json-schema-bundle#4]
As I read the readme, it should be available under `@hyperjump/json-schema-bundler`, however, there exists no such library.

**Comment by jdesrosiers** [comment]
Sorry the README is misleading. I have not published yet. That's what I plan to call it when I am ready to publish. I got most of what I wanted to get done before publishing done yesterday. I just have one more thing I want to work out before I'm ready. I hope to have v0.1.0 out soon.

**Comment by jonaslagoni** [comment]
Guess we can close this now 😄
